package de.dsheng.linturtle.model.entity;

public enum Element {
    PROCESS,
    TASK,
    USERTASK,
    SERVICETASK,
    SCRIPTTASK,
    BUSINESSRULETASK,
    EVENT,
    STARTEVENT,
    INTERMEDIATECATCHEVENT,
    INTERMEDIATETHROWEVENT,
    ENDEVENT,
    GATEWAY,
    EXCLUSIVEGATEWAY,
    PARALLELGATEWAY
}
