//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.20 at 09:28:47 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/DD/20100524/DI", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.dsheng.linturtle.domain.model.omg.spec.dd._20100524.di;
