//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.19 at 08:42:29 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/DD/20100524/DC")
package org.omg.spec.dd._20100524.dc;
